### ISSUE TITLE
トップレベル部分の改行

### ISSUE THREAD

**Issue by nissy-code** [C0A21049/ProjExD#10]
https://github.com/C0A21049/ProjExD/blob/4d65d06c85c61b4c899cc8ddee1dbe664797db16/ex05/fight_kokaton.py#L12

---

q.12, q.92など... トップレベル部分は2行空行を空けよう!!

**Comment by C0A21049** [comment]
ありがとうございます。先ほどの質問者のところで修正させていただきました
