### ISSUE TITLE
コメントアウトがほしい

### ISSUE THREAD

**Issue by nissy-code** [C0A21049/ProjExD#3]
コメントアウトで変数や関数は何をしているのかを書いてほしかったです.

Ex.) rhはrow_historyで〇〇をしている.

https://github.com/C0A21049/ProjExD/blob/70daa5f8efd644bc11ede1cb0a9f417428fe67d1/ex02/calc.py#L20

**Comment by C0A21049** [comment]
ありがとうございます。コメントを追加しました。
