### ISSUE TITLE
ここの警告文は良いと思う

### ISSUE THREAD

**Issue by c0a211211d** [C0A21049/ProjExD#4]
https://github.com/C0A21049/ProjExD/blob/70daa5f8efd644bc11ede1cb0a9f417428fe67d1/ex02/calc.py#L38

**Comment by C0A21049** [comment]
ありがとうございます。計算式が正しくないときにこれ以上の計算を行うことができなかったためその修正のために行いました。このような工夫を今後もしていきたいと思います。
