### ISSUE TITLE
同じコード?

### ISSUE THREAD

**Issue by nissy-code** [C0A21049/ProjExD#5]
91行目にも同じコードが記載されているが, なぜ2つ呼んでいるのか?

https://github.com/C0A21049/ProjExD/blob/2e1536a031519aa75494ecfcf5d607901bad7ed2/ex03/maze.py#L137

**Comment by C0A21049** [comment]
質問ありがとうございます。
91行目は再度作り直した迷路の裏側にこうかとんが行ってしまうため再度呼び出しています。
137行目は一番最初のこうかとんの描写に必要となっています。
