### ISSUE TITLE
条件分岐

### ISSUE THREAD

**Issue by nissy-code** [C0A21049/ProjExD#7]
https://github.com/C0A21049/ProjExD/blob/48db5bb4d8dc3a17eda0d12fbdb9d389bc1a98c2/ex04/dodge_bomb.py#L114-L129

if ~ 文の条件分岐をもっと簡潔にすることができればなお良かったと思いました。

**Comment by C0A21049** [comment]
orが式中に使用できなかったりと問題点が多く基本的なスイッチ文の考えを使用しました。

**Comment by C0A21049** [comment]
何を実行するコードなのかわかりやすくするためにコメントを追加させていただきました。
コメントありがとうございます。
